### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Heanhu** [yhygao/universal-medical-image-segmentation#1]
What a great job！
Could you please tell me when the code will be released?

**Comment by yhygao** [comment]
Thank you for your interest in our work. I'm working on the final clean-up of our code. We'll release it in 1-2 weeks.

**Comment by siny1998** [comment]
Hi,
Fantastic work! Do you have any plans to release the code?

**Comment by yhygao** [comment]
Sorry for the late reply due to my recent busy schedule. The code and model weights are released.
