### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by siny1998** [yhygao/universal-medical-image-segmentation#3]
Hi,

Great work on the project!
I have faced an issue in the code that I hope you can help me with. 
Specifically, there's a discrepancy in the dimensions of 'task_priors' and 'modality_priors'. 'task_priors' is structured with two dimensions, whereas 'modality_priors' includes three dimensions. This difference is causing an error during the concatenation operation.
![image](https://github.com/yhygao/universal-medical-image-segmentation/assets/119040092/c57f9534-2097-4a73-ae7f-eb3d00b3472c)

Could you please provide some guidance on how to resolve this issue?

Thank you for your assistance.

**Comment by yhygao** [comment]
Thank you for your interests in our work. 

Are you using the same datasets and code as in this repo? I tested the code in my server and everything works good. 

For task priors, as we can select multiple target tasks in each forward pass, lets say n tasks, the dimension of selected task priors (task_priors) is [B, n, dim]. For modality priors, as each image can be from a single modality, thus the dimension of selected modality priors (modality_priors) is [B, l, dim]. So they can be concatenated in the dim=1 axis to be a tensor with dimension of [B, n+l, dim]. Hope this helps. Let me know if more details are needed.

**Comment by siny1998** [comment]
Thank you for your response. I believe I've identified the cause of the error: it appears that 'idxs' should be a list rather than an integer.

**Comment by xielaobanyy** [comment]
Hello, I hope this message finds you well! May I know the version of torch you are using? I’ve encountered an issue during the installation process of "apex" and would greatly appreciate it if you could provide some guidance or share your setup details. Thank you in advance for your help!
