### ISSUE TITLE
Question about mod_priors

### ISSUE THREAD

**Issue by Heanhu** [yhygao/universal-medical-image-segmentation#4]
What a great job!
I want to ask something about self.modality_prior. Why l=10? Does this have any special meaning? Will setting different values ​​have any impact?

**Comment by yhygao** [comment]
Thanks for your interests in our work. 

The modality priors aims at capturing the the prior knowledge on features related to modality. As each imaging modality can be applied to many body region and tasks, a single token may not be enough to learn those variances. So we use more modality priors to learn such variances. The ablation of l can be found in Table 8 in the supplementary. Larger l has slightly better performance, but saturates fast.
